### ISSUE TITLE
For same sorce files，why the testcases utbot generated are different  each time？

### ISSUE THREAD

**Issue by tang4530** [UnitTestBot/UTBotCpp#320]
I generated 3 times test cases for the same source file. However, the number of test cases and the content of the test cases generated in the three times are different.
![image](https://user-images.githubusercontent.com/107664060/178205912-d1ee7243-4397-4672-bf1b-b2ba77675dab.png)

**Comment by ladisgin** [comment]
Hello @tang4530, this happened because we have nondeterministic algorithm inside UTBot, and timeout per function generation.
For better reproducing, you can enable option `Use Deterministic Searcher` and increase limit `Timeout Per Function`.
![image](https://user-images.githubusercontent.com/20314190/178452532-9e3b9d0c-4861-466c-8d12-9088fd283d3c.png)
![image](https://user-images.githubusercontent.com/20314190/178452602-0b53e75d-7790-4e29-915a-e8891afbb05c.png)
This still not guarantee same result for all runs.
