### ISSUE TITLE
KLEE performance regression after rebase to 2.3 [BUG]

### ISSUE THREAD

**Issue by ladisgin** [UnitTestBot/UTBotCpp#366]
**Description**
Performance regression about 2 times on project https://github.com/UnitTestBot/UTBotCpp/tree/main/server/test/suites/syntax
function `sort_list`

**Visual proofs (screenshots, logs)**
https://github.com/UnitTestBot/UTBotCpp/runs/7590354187?check_suite_focus=true#step:5:6400

**Comment by misonijnik** [comment]
Performance [comes back](https://github.com/misonijnik/UTBotCpp/actions/runs/2796605460) to normal if you apply this [commit](https://github.com/misonijnik/klee/commit/9c3d90a6b4f81161aa69146e797a1b034a90c71f).

KLEE optimize and prepare all code in a .bc file. To do this, among other things, it executes createCFGSimplificationPass on the code of the entire module. We once disabled this pass because it conflicts with our changes. But after moving to klee-2.3, it became clear that this pass no longer causes conflicts, so we turned it back on. Running this pass on a large file can take a fair amount of time.

Since this pass is always included in the original KLEE, I think it's worth leaving it in our version as well.

@ladisgin, how can we solve the CI problem?
