### ISSUE TITLE
[BUG] UTBot server dies on specific project with custom build script

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#490]
**Description**

**To Reproduce**
1. Clone https://github.com/libbpf/libbpf project
2. Unpack and add attached `utbot_build.sh` to the root of the project [utbot_build.zip](https://github.com/UnitTestBot/UTBotCpp/files/9766281/utbot_build.zip)
3. Unpack and replace `Makefile` from `src` with attached one 
[Makefile.zip](https://github.com/UnitTestBot/UTBotCpp/files/9766291/Makefile.zip)
4. Configure UTbot so it successfully configures on the project
5. Try to generate tests for any 'C' file in `src` folder

**Expected behavior**
Tests are generated.

**Actual behavior**
Generation fails with an error
![image](https://user-images.githubusercontent.com/10035839/195374571-93c9f93f-7479-4a3c-92ff-37bdb5fa0dfe.png)

Server process exited without any logs.

**Additional information**
I've added `utbot_build.sh` file which enters `src` folder and starts `make`.
Also `Makefile` was modified, so it outputs to `build` directory

**Comment by tyuldashev** [comment]
Let me know if whole project need to be sent to you directly. Unfortunately GitHub cannot upload it.

**Comment by kichunya** [comment]
I checked this bug on [redis](https://onebox.huawei.com/p/1b70da949914e777d295e914452d0a1c).
There are some problems with project:
1) Script utbot_build.sh:
              `make distclean`
This command does not build a project. 
Instead of this use 
              `make MALLOC=libc`
2) In addition, even if i use this command, all project builds in /redis but not in /redis/build, how it should be ( View [custom support](https://github.com/UnitTestBot/UTBotCpp/issues/451))

To check whether the server crashes because of this, I propose to fix the configuration of the project so that it is built in the /redis/build/ directory.

**Comment by tyuldashev** [comment]
After discussion it was decided to add proper handling and logging of the error which causes Segmentation fault, so server doesn't die but reports details of configuration problem.

Proper configuration of the project is out of the scope current issue.

**Comment by tyuldashev** [comment]
The server doesn't fault so often anymore even when miss-configuration happens, so we can close this case now.
